src/data-table.js, src/widget-stats.js, src/widget-trend.js, stories/data-table.stories.js
>add thousand operator on: 
- WidgetTrend
- WidgetStats
- Table
> create storybook mockup data for table
=> [G2M] Refactor - add thousand operator on values

src/data/businessData.js, src/data/categoriesData.js, src/data/provinceData.js, src/index.js, src/quick-filter-item.js, src/quick-filters.js, stories/data-table.stories.js, stories/quick-filters.stories.js
-added quick filter component
-separated data from each `stories.js`
=> [G2M] Quick Filter

src/dynamic-data-table.js, stories/data-table.stories.js
Due to the need to dynamically change the data passed to the table in covid-dash, I added a use effect that updates the state every time component re-renders
=> [G2M]Table - add useEffect to dynamically change the data rows

src/Theme/index.js, src/Theme/palette.js, src/Theme/typography.js, src/dynamic-button.js, stories/dynamic-button.stories.js
`primary`, `secondary` and `tertiary` button types are introduced.
=> [G2M]Dynamic button types added

__tests__/data-table/data-table.js, __tests__/widget-trend/widget-trend.js, package.json, src/data-table.js, src/widget-trend.js
Added additional prop testing for Data Table and Widget Trend.
=> [G2M] Added Additional unit tests to data table and widget for validity

package.json
- in addition to #25, updated version for release to 0.5.2 as changes are not breaking
=> [G2M] Update package.json version

.storybook/preview.js
accidentally commented out and committed in #34
=> [G2M] stories - revert accidental commented out theme mounting

src/table/index.js, stories/table.stories.js
also mild code refactor to group custom hook logic into `useTableConfig` custom hook
=> [G2M] table - Table.hiddenColumns prop or Table.Column.hidden prop for init hidden state

.storybook/preview.js, CHANGELOG.md, package.json, src/table/filters/default-filter.js, src/table/index.js, src/table/table-filter-label.js, src/table/table-sort-label.js, src/table/table-toolbar/download.js, src/table/table-toolbar/index.js, src/table/table-toolbar/toggle.js, stories/table.stories.js
published as [0.7.0-alpha3](https://www.npmjs.com/package/@eqworks/react-labs/v/0.7.0-alpha3)
incorporate design https://zpl.io/bzgyQNz
not all filters are implemented (only default text value filter much like the global search)
=> [G2M] Table - incorporate zpl.io/bzgyQNz

CHANGELOG.md, package.json, src/table/index.js, src/table/table-toolbar/index.js, src/table/table-toolbar/toggle.js, stories/table.stories.js
- hide toolbar when no title and no data
- Edit columns with maxHeight and auto overflow
- add initial sortBy capability
- (BREAKING) remove title property
published as ~0.8.0-alpha~ 1.0.0-alpha 🎊
=> [G2M] Table - improvements

CHANGELOG.md, package.json, src/table/filters/selection-filter.js, src/table/index.js, src/table/table-filter-label.js, src/table/table-toolbar/toggle.js, stories/table.stories.js
=> [G2M] table - react-table compatible selection-filter

CHANGELOG.md, src/table/index.js, src/table/table-toolbar/download.js, src/table/table-toolbar/index.js, src/table/table-toolbar/toggle.js
- table - additional download options to reflect filtered rows
- table - show dot badge for download when options are allowed
=> [G2M] table - download improvements

src/index.js
To fix one mistake in PR https://github.com/EQWorks/react-labs/pull/56
Change `styleCardContainer` to `styledCardContainer`
=> [G2M] structure - export StyledCardContainer

package.json, src/card.js, stories/data/date-range-filter.js, stories/data/province-dates.js, stories/table.stories.js, yarn.lock
@DoParkEQ this would be the way to pass custom filters!
this is using dates so I added mockup data.
basically just create your UI and create your filter and pass it to the table.
=> [G2M]Table - custom range filter

.storybook/main.js
fix this warning:
reference here https://github.com/storybookjs/storybook/issues/7636
=> [G2M] devops - fix storybook double config

src/image-slider/carousel.js, src/styled-card-container.js, stories/styled-card-container.stories.js
- StyledCardContainer can function as a toggle
- Carousel images are responsive to various screen size
- StyledCardContainer examples are added
=> [G2M] StyledCardContainer/Carousel enhancement

src/image-slider/top-section.js, stories/image-slider.stories.js
fixed https://github.com/EQWorks/react-labs/issues/72
=> [G2M] ImageSlider linkTo prop added

CHANGELOG.md, package.json, src/table/index.js, stories/table.stories.js
remember still works for table toggle, not for the button chosen though
=> [G2M]table - update when sort changes dynamically [build]

CHANGELOG.md, src/styled-card-container.js, src/widget-stats.js, stories/widget-stats.stories.js
=> [G2M] Widget stat/handle zero divide

CHANGELOG.md, src/button.js, src/dynamic-button.js, stories/button.stories.js, stories/dynamic-button.stories.js
=> [G2M] noSpacing prop added

CHANGELOG.md, stories/colors.stories.js, stories/shadow.stories.js, stories/typography.stories.js
Addresses #95 
- updated folder title from System to Theme
- created color palette examples.
=> [G2M] Storybook color palette example added

src/index.js, src/typography.js, stories/data/config.js, stories/typography.stories.js
=> [G2M] Typography

CHANGELOG.md, stories/shadow.stories.js
=> [G2M]Shadow story updated

.storybook/preview.js, CHANGELOG.md, src/index.js
=> [G2M] Theme/export

CHANGELOG.md, package.json, src/table/index.js, stories/table.stories.js
* add `overflow: 'visible' ` in pagination to avoid scrolling
- add the option to sort ignoring case sensitivity for strings
=> [G2M]Table patch

CHANGELOG.md, src/theme/index.js, src/theme/typography.js, src/typography.js, stories/typography.stories.js
Added secondary color configuration prop.
=> [G2M]Typography color

CHANGELOG.md, __tests__/alert/__snapshots__/alert.test.js.snap, __tests__/alert/alert.test.js, __tests__/button/button.test.js, src/alert.js, src/theme/index.js
Add tests for `<Alert />` component.
=> [G2M] Tests/Alert

.github/workflows/npm.yml, CHANGELOG.md, package.json
- update v1.10.0, changelog, and add gb action - release notes automation
=> [G2M]devops/package

CHANGELOG.md, src/chip.js, stories/chip.stories.js
=> [G2M]Chip - flexible margin control

.github/workflows/master.yml
based on last 3 commits, if encounters a semver of any type, make a release
=> [G2M] devops - add auto-release

src/index.js, src/modal-container.js, src/modal.js, src/style/layout.css, stories/modal.stories.js
modularized modal component from `snoke`
=> [G2M] Modal
